### ISSUE TITLE
[Request] Option for Stacking Inspiration

### ISSUE THREAD

**Issue by LonePaladin** [countpauper/countpauper#6]
In my game, I allow PCs to have inspiration multiple times -- up to the value of their proficiency bonus. (For instance, they're currently 8th level, so they can have up to 3 at a time.) Could you add an option to use this? Perhaps give the DM the ability to set the maximum to a specific number, or tie it to their proficiency bonus like I do, or even an ability score bonus.

In lieu of making this a universal option, I'd appreciate help in customizing the code so that I have a personal copy that behaves the way I use it.

**Comment by countpauper** [comment]
The maximum can now be set to proficiency bonus using` !svar dmi {"max":"proficiencyBonus"}`

Be aware that this does not recreate existing counters, so you'll have to delete them first. It will also not update automatically at level 13. See also `!help dmi`
